server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql:///hm35
    username: root
    password: root
  rabbitmq:
    host: 192.168.56.101
    virtual-host: /leyou
    username: leyou
    password: leyou
    template:
      exchange: LEYOU_ITEM_EXCHANGE
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15